name: source_gen
version: 4.2.0
description: >-
  Source code generation builders and utilities for the Dart build system
repository: https://github.com/dart-lang/source_gen/tree/master/source_gen
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: '>=8.1.1 <11.0.0'
  async: ^2.10.0
  build: '>=3.0.0 <5.0.0'
  dart_style: ^3.0.0
  glob: ^2.0.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  source_span: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  _test_annotations:
    path: ../_test_annotations
  build_test: ^3.3.0
  dart_flutter_team_lints: ^3.1.0
  logging: ^1.2.0
  term_glyph: ^1.2.0
  test: ^1.25.9
